"""Pterodactyl Client API wrapper: power actions and a live console/chat
websocket.

Auth uses a Client API key (looks like `ptlc_...`), generated by the user
under Account > API Credentials, scoped to the server they administer.
"""

from __future__ import annotations

import json
import threading
from collections.abc import Callable

import requests
import websocket

PowerAction = str  # "start" | "stop" | "restart" | "kill"


class PterodactylError(RuntimeError):
    pass


class PterodactylClient:
    def __init__(self, base_url: str, api_key: str, server_id: str):
        self.base_url = base_url.rstrip("/")
        self.api_key = api_key
        self.server_id = server_id
        self._session = requests.Session()
        self._session.headers.update(
            {
                "Authorization": f"Bearer {api_key}",
                "Accept": "application/json",
                "Content-Type": "application/json",
            }
        )

    # -- REST -------------------------------------------------------------------

    def _client_url(self, path: str) -> str:
        return f"{self.base_url}/api/client/servers/{self.server_id}{path}"

    def send_power_action(self, action: PowerAction) -> None:
        if action not in ("start", "stop", "restart", "kill"):
            raise ValueError(f"Unknown power action: {action}")
        resp = self._session.post(self._client_url("/power"), json={"signal": action}, timeout=15)
        if resp.status_code >= 400:
            raise PterodactylError(f"Power action '{action}' failed: {resp.status_code} {resp.text}")

    def send_command(self, command: str) -> None:
        resp = self._session.post(self._client_url("/command"), json={"command": command}, timeout=15)
        if resp.status_code >= 400:
            raise PterodactylError(f"Send command failed: {resp.status_code} {resp.text}")

    def _websocket_credentials(self) -> tuple[str, str]:
        resp = self._session.get(self._client_url("/websocket"), timeout=15)
        if resp.status_code >= 400:
            raise PterodactylError(f"Could not get websocket token: {resp.status_code} {resp.text}")
        data = resp.json()["data"]
        return data["socket"], data["token"]


# -- websocket console/chat stream ----------------------------------------------


class ConsoleStream:
    """Background websocket connection streaming console output (incl. chat).

    `on_line(text)` is called for each console output line, `on_status(status)`
    for power/state updates, both from a background thread -- marshal to the
    UI thread before touching widgets.
    """

    def __init__(
        self,
        client: PterodactylClient,
        on_line: Callable[[str], None],
        on_status: Callable[[str], None] | None = None,
    ):
        self._client = client
        self._on_line = on_line
        self._on_status = on_status
        self._ws: websocket.WebSocketApp | None = None
        self._thread: threading.Thread | None = None

    def start(self) -> None:
        socket_url, token = self._client._websocket_credentials()

        def on_open(ws):
            ws.send(json.dumps({"event": "auth", "args": [token]}))

        def on_message(ws, message):
            try:
                payload = json.loads(message)
            except json.JSONDecodeError:
                return
            event = payload.get("event")
            args = payload.get("args") or []
            if event == "console output" and args:
                self._on_line(args[0])
            elif event == "status" and args and self._on_status:
                self._on_status(args[0])
            elif event == "token expiring":
                self._refresh_token(ws)

        def on_error(ws, error):
            self._on_line(f"[connection error: {error}]")

        self._ws = websocket.WebSocketApp(
            socket_url,
            on_open=on_open,
            on_message=on_message,
            on_error=on_error,
        )
        self._thread = threading.Thread(
            target=self._ws.run_forever,
            kwargs={"origin": self._client.base_url},
            daemon=True,
        )
        self._thread.start()

    def _refresh_token(self, ws) -> None:
        try:
            _, token = self._client._websocket_credentials()
            ws.send(json.dumps({"event": "auth", "args": [token]}))
        except PterodactylError:
            pass

    def send_command(self, command: str) -> None:
        if self._ws is None:
            raise PterodactylError("Console stream not started")
        self._ws.send(json.dumps({"event": "send command", "args": [command]}))

    def stop(self) -> None:
        if self._ws is not None:
            self._ws.close()
            self._ws = None
